list
firstandthird/reporter pull request #11
Opened 2018-04-25 20:57 UTC by orthagonal

2018-05-07 21:45 UTC, jgallen23 requested changes

2018-05-07 21:45 UTC, jgallen23 commented on routes/routes.js
> +  path: '/reports',
this should be just `/`

2018-05-07 21:45 UTC, jgallen23 commented on routes/routes.js
> +// returns a table listing all registered reports:
lets rename the file to list

2018-05-07 21:45 UTC, jgallen23 commented on routes/routes.js
> +      const root = `${server.info.uri}/${key}`;
lets get this from the request host

2018-05-07 21:45 UTC, jgallen23 commented on routes/routes.js
> +        csv: `${root}.csv`,
lets add another for name that has the key

2018-05-07 21:45 UTC, jgallen23 commented on routes/routes.js
> +      const root = `${server.info.uri}/${key}`;
probably needs to check for routePrefix too

2018-05-08 19:20 UTC, orthagonal commented on routes/routes.js
> +        csv: `${root}.csv`,
What do we need here?

2018-05-08 22:24 UTC, jgallen23 commented on routes/routes.js
> +        csv: `${root}.csv`,
```
name: key,
csv: ....
```

2018-06-21 17:52 UTC, jgallen23 requested changes

2018-06-21 17:52 UTC, jgallen23 commented on routes/list.js
> +    base = request.url.host === 'https' ? `https://${base}` : `http://${base}`;
I don't think host will ever equal https, I think you want protocol.  Probably can just remove host and just use relative paths like `/reports/blah`

2018-06-25 16:56 UTC, merged